image: ubuntu:18.04

before_script:
  - apt update && apt -y full-upgrade

test:
  script:
  - doxygen doc/Doxyfile
  except:
  - master

build-linux:
  stage: build
  script: 
  - apt install -y make gcc
  - make
  artifacts:
    paths:
      - bin/projetS5
    expire_in: 1 week

build-windows:
  stage: build
  script: 
  - apt install -y make gcc-mingw-w64-x86-64
  - make CC=/usr/bin/x86_64-w64-mingw32-gcc TARGET=projetS5.exe
  artifacts:
    paths:
      - bin/projetS5.exe
    expire_in: 1 week

pages:
  script: 
  - apt update && apt install -y doxygen graphviz
  - doxygen doc/Doxyfile
  - mv doc/webdoc/html/ public/
  artifacts:
    paths:
    - public
  only:
  - master
