image: alpine:latest

before_script:
  - apk update -q && apk add -q --no-cache gcc make musl-dev
  - mkdir bin
  - mkdir obj

build:
  stage: build
  script: make
  artifacts:
    paths:
      - bin
