image: ubuntu:18.04

before_script:
  - apt update && apt -y full-upgrade
  - apt install -y gcc make mingw-w64
  - mkdir bin
  - mkdir obj

build-linux:
  stage: build-linux
  script: make
  artifacts:
    paths:
      - bin

build-windows:
  stage: build-windows
  script: 
  - ./configure --host=x86_64-w64-mingw32
  - make
  artifacts:
    paths:
      - bin
