image: ubuntu:18.04

before_script:
  - apt update
  - apt -y full-upgrade

test:
  script:
  - apt update
  - apt install -y doxygen graphviz
  - cd doc
  - doxygen Doxyfile
  except:
  - master

build-linux:
  stage: build
  script: 
  - apt install -y make gcc
  - make
  - mv bin/projects5 ./
  artifacts:
    paths:
      - projects5
    expire_in: 1 week

build-windows:
  stage: build
  script: 
  - apt install -y make gcc-mingw-w64-x86-64
  - make CC=/usr/bin/x86_64-w64-mingw32-gcc TARGET=projects5.exe
  - mv bin/projects5.exe ./
  artifacts:
    paths:
      - projects5.exe
    expire_in: 1 week

pages:
  script: 
  - apt update
  - apt install -y doxygen graphviz
  - cd doc
  - doxygen Doxyfile
  - mv webdoc/html/ ../public/
  artifacts:
    paths:
    - public
  only:
  - master
