image: ubuntu:18.04

before_script:
  - apt update && apt -y full-upgrade

build-linux:
  stage: build
  script: 
  - apt install -y make gcc
  - make
  artifacts:
    paths:
      - bin/projetS5
    expire_in: 1 week

build-windows:
  stage: build
  script: 
  - apt install -y make gcc-mingw-w64-x86-64
  - make CC=/usr/bin/x86_64-w64-mingw32-gcc TARGET=projetS5.exe
  artifacts:
    paths:
      - bin/projetS5.exe
    expire_in: 1 week
