image: ubuntu:18.04

before_script:
  - apt update && apt -y full-upgrade
  - apt install -y build-essential autoconf mingw-w64
  - mkdir bin
  - mkdir obj

build:
  stage: build
  script: 
  - make
  - make CC=x86_x64-w64-mingw32-gcc
  artifacts:
    paths:
      - bin
