image: ubuntu:18.04

before_script:
  - apt update && apt -y full-upgrade
  - mkdir bin
  - mkdir obj

build-linux:
  stage: build
  script: 
  - apt install -y make gcc
  - make
  artifacts:
    paths:
      - bin

build-windows:
  stage: build
  script: 
  - apt install -y make gcc-mingw-w64
  - make CC=x86_x64-w64-mingw32-gcc
  artifacts:
    paths:
      - bin
