image: ubuntu:18.04

before_script:
  - apt -qq update && apt -y -qq full-upgrade
  - apt install -qq -y build-essential autoconf mingw-w64
  - mkdir bin
  - mkdir obj

build:
  stage: build
  script: 
  - make
  - export PATH=/mingw64/bin:$PATH
  - ./configure --host=x86_64-w64-mingw32
  - make
  artifacts:
    paths:
      - bin
